name: stale

on:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 90
          days-before-close: 30
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity in 90 days. It will be closed in 30 days if no further activity occurs.
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not had
            activity in 90 days. It will be closed in 30 days if no further activity occurs.
          close-issue-message: >
            This issue was automatically closed due to inactivity.
          close-pr-message: >
            This PR was automatically closed due to inactivity.
